barca_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-dbt
      user: dbt-barca
      password: dbt-barca
      port: 5432
      dbname: "dbt-barca_db"
      schema: public